### ISSUE TITLE
Not correct behavior in case of parameter value less or equal than 21

### ISSUE THREAD

**Issue by geryla** [jakubgereg/url-and-query#1]
If URL is like this: /cbd/8625439-cbd-produkty?parameter[15]=1 and parameter is basically less than 21, it not works correctly. 

Explanation should be: The problem arises because when the parameter index is less than 21, it’s parsed as a single number, but when it’s 21 or greater, it’s parsed as a string.

Expected result should be:

`baseUrl: "/cbd/8625439-cbd-produkty",
        queryParams: {
          parameter: {
            15: "1",
          },
        },`

but is like:

`"parameter": Array [
  "1",
 ],`

<img width="403" alt="Snímek obrazovky 2024-05-09 v 10 52 13" src="https://github.com/jakubgereg/url-and-query/assets/74047050/4fd8426b-7826-473d-badf-c82b2fe52190">

Thank you for your help!

**Comment by jakubgereg** [comment]
not an issue with this library.

This is default behaviour of qs library see:

https://www.npmjs.com/package/qs

`
qs will also limit specifying indices in an array to a maximum index of 20. Any array members with an index of greater than 20 will instead be converted to an object with the index as the key. This is needed to handle cases when someone sent, for example, a[999999999] and it will take significant time to iterate over this huge array.
`

you can disable it by passing either 

`{ parseArrays: false }` or `{ arrayLimit: 0 }` option to `parseOptions`
